language: ruby
before_install:
  - gem install bundler
matrix:
  include:
    - rvm: 2.3.1
      gemfile: Gemfile
    - rvm: 2.4.1
      gemfile: Gemfile
    - rvm: 2.5.0
      gemfile: Gemfile
      script: bundle exec rake && bundle exec rubocop
